### ISSUE TITLE
fail install chromium on RetroPie 4.3

### ISSUE THREAD

**Issue by erwanJarno** [zerojay/RetroPie-Extra#251] opened 2017-11-20 17:04 UTC
On fresh 4.3 install

```
$ sudo su -
# grep __version /home/pi/RetroPie-Setup/retropie_packages.sh
__version="4.3"
# git clone https://github.com/zerojay/RetroPie-Extra.git
# cd RetroPie-Extra/
# ./install-extras.sh
# cd /home/pi/RetroPie-Setup
# ./retropie_packages.sh chromium
# reboot
```

I gets :

boost::filesystem::filesystem_error
boost::filesystem::status: Permission denied: /root/RetroPie/roms/ports

**Comment by zerojay** [comment] 2017-11-20 22:54
Shouldn't be happening as it shouldn't be attempting to run it as root. Did you set up X so that anyone could run it yet, as shown on the main page of the repo?

**Comment by zerojay** [comment] 2017-11-20 22:59
Not the first time I've seen someone report it though.

**Comment by zerojay** [comment] 2017-11-21 01:53
What happens if you run the installation of chromium through RetroPie-Setup as selected from emulationstation?

**Comment by symbios24** [comment] 2017-11-21 08:12
Installation works 100% from the setup script.

**Comment by zerojay** [comment] 2017-11-21 08:24
Installation should only be done through the setup script. Installing from directly running ./retropie_packages isn't something guaranteed as it's likely the RetroPie-Setup script does something like drops permissions back to the pi user before running it or something along these lines. @erwanJarno, can you please delete the package's installation and run it through RetroPie-Setup as intended and see if you get the same issues?

**Comment by symbios24** [comment] 2017-11-21 08:31
The only thing is that the latest chrome is version 62 and the script installs version 56 can this be corrected?

Thanks

**Comment by zerojay** [comment] 2017-11-21 08:33
As far as I'm aware, it's installing whatever the latest version of the package is in Raspbian.

**Comment by symbios24** [comment] 2017-11-21 08:35
So only raspbian stretch can have the latest version as i see.
thanks

**Comment by erwanJarno** [comment] 2017-11-21 11:09
my full proc :
```

### main computer
sudo su -
df -h
diskutil list
diskutil unmountDisk /dev/disk4
set +o posix
dd bs=4m if=<(gunzip < /Users/me/Downloads/retropie-4.3-rpi1_zero.img.gz) of=/dev/rdisk4;sync
diskutil unmountDisk /dev/disk4


### Raspberry
passwd
sudo systemctl enable ssh
sudo systemctl start ssh


### main computer
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no pi@10.0.0.10
sudo su -
#git -C /home/pi/RetroPie-Setup/ show
grep __version /home/pi/RetroPie-Setup/retropie_packages.sh
HOSTNAME="mypi"
printf "${HOSTNAME}" > /etc/hostname
sed -r -i 's/^(127.0.1.1[ \t]*).*$/\1'"${HOSTNAME}"'/' /etc/hosts
/etc/init.d/hostname.sh
CONFIG_FILE="/boot/config.txt"
KEY='hdmi_force_hotplug';VALUE='1';sed -r -i 's/^#?('"${KEY}"' *= *).*$/\1'"${VALUE}"'/' "${CONFIG_FILE}"
KEY='hdmi_drive';VALUE='2';sed -r -i 's/^#?('"${KEY}"' *= *).*$/\1'"${VALUE}"'/' "${CONFIG_FILE}"
exit
export http_proxy=http://$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_SERVER:$PROXY_PORT
#https://github.com/zerojay/RetroPie-Extra
git clone https://github.com/zerojay/RetroPie-Extra.git
cd RetroPie-Extra/
./install-extras.sh
sudo su -
export http_proxy=http://$PROXY_USERNAME:$PROXY_PASSWORD@$PROXY_SERVER:$PROXY_PORT
cd /home/pi/RetroPie-Setup
./retropie_setup.sh #(accept root add to input and video groups) Manage Packages -> Manage experimental packages -> 310/chromium
dpkg-reconfigure xserver-xorg-common
reboot

```

Output :
```
# dpkg-reconfigure xserver-xorg-common
dpkg-query: package 'xserver-xorg-common' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
/usr/sbin/dpkg-reconfigure: xserver-xorg-common is not installed
```
```
# reboot
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
 what(): boost::filesystem::status: Permission denied: "/root/RetroPie/roms/ports"
Aborted
```

**Comment by symbios24** [comment] 2017-11-21 11:30
why going to all this trouble while you can install it from the setup-script so easy.

**Comment by erwanJarno** [comment] 2017-11-21 13:12
in this version I have use setup-script :
`./retropie_setup.sh #(accept root add to input and video groups) Manage Packages -> Manage experimental packages -> 310/chromium`

**Comment by symbios24** [comment] 2017-11-21 13:27
setup script need to run with sudo

**Comment by zerojay** [comment] 2017-11-21 13:31
#(accept root add to input and video groups) <--- There is no request to add root to any groups as part of retropie_setup.sh and I suspect that this is your problem. You're somehow running things as root when they should not be which is why you are getting "/root/RetroPie/roms/ports" permissions errors.

**Comment by zerojay** [comment] 2017-11-21 13:35
Also, I've corrected the command to ask for permission for other users to run X (which I could swear I had done before but...)

The Chromium installation script should properly install the app you need and the readme is now updated to give you the proper command to run. Give it another shot and let me know.

**Comment by erwanJarno** [comment] 2017-11-21 14:55
insted of using :
`export http_proxy=http://${PROXY_USERNAME}:${PROXY_PASSWORD}@${PROXY_SERVER}:${PROXY_PORT}`
I have use :
`echo 'Acquire::http::Proxy "http://'/${PROXY_USERNAME}:${PROXY_PASSWORD}@${PROXY_SERVER}:${PROXY_PORT}'";' > /etc/apt/apt.conf.d/10proxy`
And lauched retropie setup from GUI

It worked

**Comment by symbios24** [comment] 2017-11-21 15:20
why dont you just try to reset the permissions from the script.

**Comment by zerojay** [comment] 2017-11-21 16:43
Okay, so we can close this as fixed then?

**Comment by erwanJarno** [comment] 2017-11-21 16:54
yesn, thanks you for help

**Closed** 2017-11-21 16:55 UTC
Labels: bug
